name: Preview
on:
  push:
    branches:
      - master
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    env:
      NX_BRANCH: ${{ github.event.number }}
      NX_RUN_GROUP: ${{ github.run_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install Dependencies
        run: |
          npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}"
          npm install
      - name: Storybook Docs
        run: npm run sb:docs
      - name: Storybook Build
        run: npx nx run ui-storybook:build-storybook
      - name: Website Build
        run: npm run build:ssr
      - name: Best Of Build
        run: npx nx run best-of:build:production
      - name: Api Build
        run: npx nx run api:build:production
      - name: Web Socket Build
        run: npx nx run web-socket:build:production
      - name: Docker Copy Files
        run: npm run dc:copy
      - name: Docker Install Production Dependencies
        run: |
          npm install --production
        working-directory: ./tools/ci/dist
      - name: Docker Install Optional Dependencies
        run: |
          npm config set '//npm.fontawesome.com/:_authToken' "${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}"
          npm install --optional
        working-directory: ./tools/ci/dist
      - name: Pulumi Install CLI
        uses: pulumi/setup-pulumi@v2
      - name: Pulumi Install Dependencies
        run: npm install
        working-directory: ./tools/ci/
      - name: Pulumi Preview
        uses: pulumi/actions@v3
        with:
          work-dir: ./tools/ci/
          command: preview
          stack-name: ci
        env:
          ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
          ARM_CLIENT_SECRET: ${{secrets.ARM_CLIENT_SECRET}}
          ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
          ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          NX_DRP_API_ADMIN_KEY: ${{ secrets.NX_DRP_API_ADMIN_KEY }}
          NX_AUTH0_CLIENT_ID: ${{ secrets.NX_AUTH0_CLIENT_ID }}
          NX_AUTH0_CLIENT_SECRET: ${{ secrets.NX_AUTH0_CLIENT_SECRET }}
          NX_TINY_PNG_API_KEY: ${{ secrets.NX_TINY_PNG_API_KEY }}
          NX_AYRSHARE_API_KEY: ${{ secrets.NX_AYRSHARE_API_KEY }}
